// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.
// </auto-generated>

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace Kontent.Ai.Boilerplate.Models.ContentTypes
{
    public partial class HostedVideo
    {
        public const string Codename = "hosted_video";
        public const string VideoHostCodename = "video_host";
        public const string VideoIdCodename = "video_id";

        public IContentItemSystemAttributes System { get; set; }
        public IEnumerable<IMultipleChoiceOption> VideoHost { get; set; }
        public string VideoId { get; set; }
    }
}